apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd3-poc-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cd3-poc-app
  template:
    metadata:
      labels:
        app: cd3-poc-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}