apiVersion: v1
kind: Service
metadata:
  name: cd3-poc-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: cd3-poc-app