apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd3-poc-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rapidghi/cd3-poc-gitops.git # <-- IMPORTANT: Change 'rapidghi' to your GitHub username and the repo name if different
    targetRevision: HEAD
    path: apps/cd3-poc-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true